# Generated by Django 4.2.2 on 2023-06-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('case_details', models.TextField()),
                ('communication_method', models.CharField(max_length=20)),
                ('case_category', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
