# Generated by Django 4.2.2 on 2023-06-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_clientapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapplication',
            name='communication_method',
        ),
    ]
