# Generated by Django 4.2.2 on 2023-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_clientapplication_communication_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
