# Generated by Django 4.2.2 on 2023-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_clientapplication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
