# Generated by Django 4.2.2 on 2023-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_clientapplication_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapplication',
            name='is_approved',
        ),
    ]
