# Generated by Django 4.2.2 on 2023-06-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_clientapplication_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(max_length=10)),
            ],
        ),
    ]
