# Generated by Django 4.2.2 on 2023-06-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_case_approval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case_approval',
            new_name='approval',
        ),
    ]
