# Generated by Django 4.2.2 on 2023-06-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_rename_case_approval_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='approval_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.approval'),
        ),
    ]
