# Generated by Django 4.2.2 on 2023-06-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
