# Generated by Django 4.2.2 on 2023-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_delete_message_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('message', models.TextField()),
            ],
        ),
    ]
