# Generated by Django 4.2.2 on 2023-06-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_message_room_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
