# Generated by Django 4.2.2 on 2023-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='names',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
