# Generated by Django 4.2.2 on 2023-06-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_message_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='names',
        ),
    ]
