# Generated by Django 4.2.2 on 2023-06-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_message_content_alter_message_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='names',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
