# Generated by Django 4.2.2 on 2023-07-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_usermanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclients',
            old_name='full_name',
            new_name='full_name3',
        ),
        migrations.RenameField(
            model_name='userclients',
            old_name='user',
            new_name='user3',
        ),
        migrations.RenameField(
            model_name='usermanager',
            old_name='full_name',
            new_name='full_name2',
        ),
        migrations.RenameField(
            model_name='usermanager',
            old_name='user',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='full_name1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user1',
        ),
    ]
