# Generated by Django 4.2.2 on 2023-07-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_rename_full_name_userclients_full_name3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclients',
            old_name='full_name3',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userclients',
            old_name='user3',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usermanager',
            old_name='full_name2',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='usermanager',
            old_name='user2',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name1',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user1',
            new_name='user',
        ),
    ]
