# Generated by Django 4.1.4 on 2023-07-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_rename_full_name3_userclients_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
