# Generated by Django 4.1.4 on 2023-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_delete_usermanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_full_name', models.CharField(max_length=255)),
                ('manager_email', models.CharField(max_length=255)),
                ('manager_password', models.CharField(max_length=255)),
            ],
        ),
    ]
