# Generated by Django 4.1.4 on 2023-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_manager_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_full_name', models.CharField(max_length=255)),
                ('lawyer_email', models.EmailField(max_length=255)),
                ('lawyer_password', models.CharField(max_length=255)),
            ],
        ),
    ]
